### PR TITLE
Add Support for Ubuntu 20.10

### PR DESCRIPTION
**Pull request by hswong3i**
Similar as https://github.com/lavabit/robox/pull/145 but using new https://releases.ubuntu.com/20.10/ubuntu-20.10-live-server-amd64.iso (because I couldn't find the `ubuntu-legacy-server` version).

P.S. Seems new live iso require a new automated server Installation procedure: 
- https://ubuntu.com/server/docs/install/autoinstall
- https://ubuntu.com/server/docs/install/autoinstall-quickstart
- https://ubuntu.com/server/docs/install/autoinstall-reference
- https://nickcharlton.net/posts/automating-ubuntu-2004-installs-with-packer.html

### CODE REVIEW

**Comment by hswong3i** [comment]
Close as per https://github.com/lavabit/robox/commit/15ff9f1450d0e05552da05f6fc8b2f6be87cc65e

**Comment by ladar** [comment]
Hi @hswong3i I added the Ubuntu 20.10 target, but the auto install file will need to be completely overhauled to work with the live ISOs, and I haven't done that yet. If anyone wants to work on it, it's the http/generic.ubuntu2010.vagrant.cfg file. Of course the boot command will also need updating.

**Comment by hswong3i** [comment]
@ladar Oh threfore I will try to rebase and revoke this PR? As I am HEAVILY using image from this repo DAILY, I would like to learn and give a hand for contribution if possible ;-)

**Comment by ladar** [comment]
@hswong3i I spent a few hours and overhauled the 20.10 autoinstall config. The new boxes are being uploaded with the `3.1.0`` release.

It was particularly hard because the new installer isn't very well documented, and there were even fewer real world examples to pull from, so these box images may need further work. Can you please test them out, and let me know if there are any issues? 

And/or submit pull requests with any requisite cleanup/improvements. I was focused on getting the installer working, so I've spent almost no time trying to use the end result.

**Pull request closed without merging**
