### PR TITLE
#139 Add generic-ubuntu2004-libvirt for Ubuntu 20.04 release

### PR DESCRIPTION
**Pull request by abbbi**
hi,
adds needed files to build vagrant image for the just released ubuntu 20.04 beta.

### CODE REVIEW

**Comment by hswong3i** [comment]
@abbbi you could use `git rebase -i lavabit/master` to regroup your multiple commit into single for PR ;-)

**Comment by abbbi** [comment]
> @abbbi you could use `git rebase -i lavabit/master` to regroup your multiple commit into single for PR ;-)

the first pull request was multiple commit, now its a single one, as i closed the first pull request and reopened with single commit.

**Comment by hswong3i** [comment]
> > @abbbi you could use `git rebase -i lavabit/master` to regroup your multiple commit into single for PR ;-)
> 
> the first pull request was multiple commit, now its a single one, as i closed the first pull request and reopened with single commit.

After rebase, you could also use git push --force to update your own github fork, the PR with show only one commit, finally

**Comment by abbbi** [comment]
im sorry if im wrong here, but this PR only shows one commit?: merge 1 commit

**Comment by hswong3i** [comment]
> im sorry if im wrong here, but this PR only shows one commit?: merge 1 commit

This PR is totally fine.

What I mean is you don't really need to clone the original PR and reopen as this PR:

- Just simply `git fetch lavabit && git rebase -i lavabit/master && git push --all --force -u origin`
- This could help you merge your local repo and force push to your github repo
- Then the PR will show it as single commit.

**Comment by nvtkaszpir** [comment]
notice that ubuntu server 20.04 introduces new autoinstaller (actuallly it's just cloud-init)
https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls

**Comment by abbbi** [comment]
> notice that ubuntu server 20.04 introduces new autoinstaller (actuallly it's just cloud-init)
> https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls

yes, using the new live installer images its only possible to use the new cloud-init based preseeding style. Using the legacy installation images for 20.04 it still seems possible to use the standard d-i preseed stuff.

**Comment by timschumi** [comment]
I already have a patchset locally which I already tested for libvirt and virtualbox (also in line with the recently merged changes). We'll have to see which one is more fit for merging.

**Comment by ladar** [comment]
These changes were incorporated into PR #145.

**Pull request closed without merging**
