### PR TITLE
Add support for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by timschumi**
Still using the legacy installer, since the automatic installation would have to be significantly reworked otherwise.

### CODE REVIEW

**Comment by timschumi** [comment]
Test-built on virtualbox and libvirt so far. Still contains some conflicts. For now, only for comparison against other patchsets.

**Comment by ladar** [comment]
@timschumi I'd like to add Ubuntu 20.04 to the upcoming release. This looks more complete than PR #141, but I'm wondering whether we need to cherry pick any changes from that patch before merging.

**Comment by timschumi** [comment]
> @timschumi I'd like to add Ubuntu 20.04 to the upcoming release. This looks more complete than PR #141, but I'm wondering whether we need to cherry pick any changes from that patch before merging.

I diffed my set of changes against the other PR (which is based on 19.04 instead of 19.10), and I found only the following differences:
- Hyper-V, Parallels, VirtualBox and vmware support on my side.
- Different boot command key sequence (is a 19.04 vs 19.10 diffference)
- Two remaining occurrences of 19.04 replaced (hostname and comment about support end)
- libvirt disk bus is SCSI (like 19.10) instead of VirtIO (was apparently changed for 19.04)

Apart from that, there are no differences that I could spot in git diff. As already mentioned, test builds in libvirt and VirtualBox are working fine,

**Comment by ladar** [comment]
Merging... we'll see what happens during the 3.0.0 build.

**Pull request merged**
