### PR TITLE
RHEL8: does not boot with disk_bus=scsi #17

### PR DESCRIPTION
**Pull request by abbbi**
see issue #17

### CODE REVIEW

**Comment by ladar** [comment]
Switched to "virtio" per our discussion. Please let me know if the change is necessary for the other RHEL based images (Oracle 7, CentOS 6/7 and RHEL 6/7) or limited to RHEL 8? If the latter we may want to open a ticket with RH.

**Comment by abbbi** [comment]
hi again,

i have others on the system which use the scsi setting and do not fail, for example generic/debian8. So it might indeed be a issue related to RHEL8.

**Comment by ladar** [comment]
@abbbi can you confirm the [RHEL 8.0 v1.8.52](https://app.vagrantup.com/generic/boxes/rhel8/versions/1.8.52) box solves this problem, and if so, close the PR? Thank you.

**Comment by ladar** [comment]
Assuming fixed. Closing.

**Pull request closed without merging**
