### PR TITLE
Use sata adapter for rhel8 remove ide

### PR DESCRIPTION
**Pull request by nilsmeyer**
Changes the RHEL8 box to use a SATA Controller instead of IDE, making it easier to add drives later as well as potentially offering performance benefits. The IDE Controller is removed by packer.

### CODE REVIEW

**Comment by ladar** [comment]
@nilsmeyer right now the configs omit this variable, thus using the default IDE interface. It doesn't make sense to update only the RHEL 8 config. If there are legit reasons for making this change, it should at least apply to all RHEL derivatives... and probably the latest Alpine/Fedora/Ubuntu/Debian configs as well. 

Also, we'll probably need to switch the ISO interface to SATA as well. 

Can you point to any Vbox documentation which suggests SATA over IDE, and any potential compatibility issues? For example NVMe is superior but requires VBox 6+ with the extension pack, so it can't be used.

**Comment by ladar** [comment]
Also, the bundled Vagrantfile templates might need to be updated to configure SATA controllers if this change is approved.

**Comment by nilsmeyer** [comment]
@ladar 
Thank you for looking at this. The reason why I'm switching to SATA was that I needed to attach additional drives which is easier with a virtual SATA Controller (no messing with master/slave etc.) and AHCI is pretty well supported in all modern operating systems. I've heard mention of performance benefits but the documentation doesn't bear this out. 

I only made this change for RHEL8 (and later Debian) because those were the images I was using, changing this globally for all operating systems makes more sense in my opinion. This may break setups that assume an IDE controller though. 

I would ask however whether there is a good reason *not* to use SATA? I'm not sure why packer defaults to IDE.

**Comment by ladar** [comment]
Emulating a SCSI controller was the original solition, followed by IDE. Then came the pass through virtual devices. which the VirtualBox builder appears to think of as NVMe. Switching to NVMe should offer a big performance boost, which probably won't happen with a switch from IDE to SATA. (SATA is literally serialized ATA, and ATA is basically the IDE protocol).

Anyways, the reason not make the change is that it might cause breakage. Keep in mind we have 46 distros at this point, and it's hard to say what will happen if we switch to SATA. I'm also worried that SATA might be handled differently by Vagrant on the various hosts, and/or across the different VirtualBox releases 5.x versus 6.x. 

Issue #125 captures this same headache, but with the libvirt/qemu systems. Namely finding a set of options that works for every guest/host/box. 

That said, if you can make a compelling case, and we identify which guests should be changed, it could work. The hard part will be testing the change with`packer` and then `vagrant` before merging, so we don't break the build pipeline.

**Comment by ladar** [comment]
@nilsmeyer if you consult issue #125 you'll see how tricky changing the virtual hardware can be. I don't think I understand why using `sata` will make it easier to add extra drives? Is it simply having the extra ports? Is there a particular reason the boot drive must use SATA? Or can you simply add a new, empty, SATA bus, and then add your drives to it? I feel like I'm missing something.

**Comment by nilsmeyer** [comment]
I think switching this for everyone is likely to cause issues down the line, so I will close this pull request. 

For me, the SATA controller makes it a bit easier to add drives simply because I don't have to worry about the ATA Master/Slave. I'm not good enough with Ruby to determine in my Vagrantfile what controller is used and what other drives may be present, so this is mostly for my convenience/laziness. Adding another controller didn't seem as portable to me and I don't want to run into issues with the OS enumerating the drives differently.

**Pull request closed without merging**
