### PR TITLE
Add a i386 debian9 box (debian9x86)

### PR DESCRIPTION
**Pull request by timschumi**
A Debian i386 box is probably one of the more interesting targets.
It is often used as a clean image to build software (in parts due to high
compatibility and stability), but still lacks full multiarch support (e.g. conflicting files on x86 and x64).

Having an image for this would help with setting up 32-bit build environments (or other things that need x86).

I'm open to better names for this box, but I couldn't think of anything.

### CODE REVIEW

**Comment by ladar** [comment]
I've been toying with the idea of adding alternate architectures for awhile, but haven't taken the time because there doesn't seem to be enough interest to justify the added build time/complexity. If you look at the various other x32 (aka i386/i686) builds on the Vagrant Cloud they only get a handful of downloads. 

I've been wanting to open a feature request with `vagrant` for awhile that would allow me to upload alt architectures versions and specify the arch like we do the provider. So if someone picked `generic/debian9` they would see the provider list, and if they chose `libvirt` they might see `i386`, `x86_64` and `arm` ... which would at least keep the repos clean.

If you'd like to experiment, let's start small and pick one provider (libvirt, vmware or vbox), and create a `generic-xxx-x86.json` file, and then add the Debian 9 config to it. 

The real issue is what config modules will need changes for i386. I suspect the changes will be extremely minor for most distros, so a simple `bash` `if/else` should suffice. You should be able to use `uname -m` or `uname -p` to catch 32 bit builds.

P.S. I'll be counting on you @timschumi to then maintain the generic-xxx-x86.json files.

**Comment by timschumi** [comment]
> If you'd like to experiment, let's start small and pick one provider (libvirt, vmware or vbox), and create a `generic-xxx-x86.json` file, and then add the Debian 9 config to it.

This sounds like a much better idea than what I had in mind here. Especially if we can avoid duplicating all the scripts again. I can prepare a PR the next few days, but I'll probably need a bit of help to do the wiring-up at the top level.

> 
> The real issue is what config modules will need changes for i386. I suspect the changes will be extremely minor for most distros, so a simple `bash` `if/else` should suffice. You should be able to use `uname -m` or `uname -p` to catch 32 bit builds.

Changes for i386 have been minimal to nonexistent so far on Debian (at least I don't recall making any changes, certainly thanks to apt automatically abstracting the default architecture).

> 
> P.S. I'll be counting on you @timschumi to then maintain the generic-xxx-x86.json files.

I'd certainly be happy to. I've been regularly using the image proposed here for my own projects, so I can keep an eye on it.

**Comment by ladar** [comment]
In terms of wiring up, there isn't much you need to do. Just search the `robox.sh` script for the string `generic-xxx.json` (where xxx is the provider) and add `generic-xxx-x86.json`. There is a variable with all the files that used for some parsing logic. And a couple pipeline functions. Plus the `box()` function. When you're done, the new file will be added to the build pipeline and let you can use the `./robox.sh box yyy` shortcut (or `./robox.sh generic-xxx-x86` command) to test.

You'll also want to add the new ISO to the `packer-cache.json` file so the build pipeline doesn't get stuck waiting for the ISO to download.

**Comment by ladar** [comment]
I should have said, search for `generic-xxx-x86` as there are a few places where the file extension isn't included.

Also, a side note on naming. Do you have an opinion on `x86` / `x86_64` vs `x32` / `x64` vs `i386` or `i686`?

**Comment by timschumi** [comment]
> Also, a side note on naming. Do you have an opinion on `x86` / `x86_64` vs `x32` / `x64` vs `i386` or `i686`?

I'd have to say `x32/x64` there. I tend to often use `x86/x64`, but that isn't a "valid" combination, and the `x86_64` is just uncomfortable to type/read in my opinion.

**Comment by ladar** [comment]
I also personally prefer `x32` and `x64` so let's use that for the file/box name.

**Comment by timschumi** [comment]
This is what I had drafted up so far.

For the `robox.sh` functions, I introduced a `generic-libvirt-x32` function and argument, all the other functions (`generic()`, `libvirt()`, etc.) I just added the x32 target so that it is included automatically.

Since build name generation splits the name on dashes, so I simply hardcoded `-x32-` it into the postprocessors part. If it doesn't cause any problems with your deployment setup, we might want to think about switching to a different seperator.

I'm also unsure whether I should add libvirt-x32 to where the `$GENERIC_BOXES` variable is generated.

**Comment by ladar** [comment]
I think it's worth mentioning that when we roll out `x32` to other providers/distros, etc, I plan to add `x64` to all of the existing filenames, box configurations to make it clear. I just figured that step should wait till this effort moves out of the experimental phase.

To that end, `provider-arch` (aka `libvirt-x32`) works for file names, but I'm wondering if it makes more sense to use `org-distro-arch-provider` (aka `generic-debian-x32-libvirt` for the box name, and adjust the artifact name to match. I could go either way on that, and we can always switch it up later, which is why I didn't mention it along with my code review.

**Comment by timschumi** [comment]
> The only issues I noticed while looking it over was GENERIC_TAGS is looking for `x86` not `x32`.

Done.

> And you used `debian9` for the `packer-cache.json` change, which will conflict with the existing `debian9` config in that file.

So far it seemed to work. Anyways, I now changed the name to "debian-x32", along with the output directory (is that even used?).

> To that end, `provider-arch` (aka `libvirt-x32`) works for file names, but I'm wondering if it makes more sense to use `org-distro-arch-provider` (aka `generic-debian-x32-libvirt` for the box name, and adjust the artifact name to match.

Appending `-x32` (or `-x64` for that matter) would make a bit more sense, but there are a lot of cases where the build name is simply split by dashes and accessed by indexes, so that would have to be rewritten to be more resilient.

**Comment by ladar** [comment]
> Appending -x32 (or -x64 for that matter) would make a bit more sense, but there are a lot of cases where the build name is simply split by dashes and accessed by indexes, so that would have to be rewritten to be more resilient.

I can take care of that when we graduate and I adjust the existing templates so they include `x64`. Basically the current convention is ORG-REPO-PROVIDER. So these new boxes would get uploaded to a repo called `generic/debian9-x32` ... of course we have a little time before we decide where to publish the 32 bit boxes. First we need to see if they build properly and work properly with Vagrant, etc.

P.S. It's interesting that you chose Debian 9, because all of the Debian 9 build attempts (Hyper-V, VMware, libvirt) have failed. They hang for an hour waiting for an SSH connection. I caught one, and it was stuck on the `pkgsel` step, so there must be an issue with the auto install config. Have you tested this Debian 9 build config recently?

**Comment by ladar** [comment]
> I caught one, and it was stuck on the pkgsel step, so there must be an issue with the auto install config. Have you tested this Debian 9 build config recently?

I just updated the Debian 9 config file so it will use the archive repo instead of it's mirror list. Perhaps the reason those boxes failed was because the Debian 9 repos were recently removed from the mirror sites.

**Comment by timschumi** [comment]
> I caught one, and it was stuck on the `pkgsel` step, so there must be an issue with the auto install config. Have you tested this Debian 9 build config recently?

Huh, I was just building a "normal" Debian 9 box a few hours ago to ensure that I didn't break anything, everything went fine there.

Rerunning one now automatically chooses the ftp.us.debian.org mirror and it successfully manages to do the initial setup and establish an SSH connection.

**Comment by ladar** [comment]
My mistake, it appears the Debian 8 builds are failing, and not Debian 9. I'll have to remove (comment out) the change I made to the auto install config.

**Comment by ladar** [comment]
```
[ladar@walter output]$ ls *debian*
generic-debian10-libvirt-3.0.0.box         roboxes-debian10-libvirt-3.0.0.box
generic-debian10-libvirt-3.0.0.box.sha256  roboxes-debian10-libvirt-3.0.0.box.sha256
generic-debian10-vmware-3.0.0.box          roboxes-debian10-vmware-3.0.0.box
generic-debian10-vmware-3.0.0.box.sha256   roboxes-debian10-vmware-3.0.0.box.sha256
generic-debian9-libvirt-3.0.0.box          roboxes-debian9-libvirt-3.0.0.box
generic-debian9-libvirt-3.0.0.box.sha256   roboxes-debian9-libvirt-3.0.0.box.sha256
generic-debian9-vmware-3.0.0.box           roboxes-debian9-vmware-3.0.0.box
generic-debian9-vmware-3.0.0.box.sha256    roboxes-debian9-vmware-3.0.0.box.sha256
```

```
logs/generic-vmware-1.txt:2020/04/30 13:38:02 ui: generic-debian8-vmware output will be in this color.
logs/generic-vmware-1.txt:2020/04/30 13:38:02 Preparing build: generic-debian8-vmware
logs/generic-vmware-1.txt:2020/04/30 16:32:55 Parallelization disabled, waiting for build to finish: generic-debian8-vmware
logs/generic-vmware-1.txt:2020/04/30 16:32:55 Starting build run: generic-debian8-vmware
logs/generic-vmware-1.txt:2020/04/30 16:32:55 ui: ==> generic-debian8-vmware: Retrieving ISO
logs/generic-vmware-1.txt:2020/04/30 16:32:55 ui: ==> generic-debian8-vmware: Trying https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso
logs/generic-vmware-1.txt:2020/04/30 16:32:55 ui: ==> generic-debian8-vmware: Trying https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso?checksum=sha256%3Aea444d6f8ac95fd51d2aedb8015c57410d1ad19b494cedec6914c17fda02733c
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui: ==> generic-debian8-vmware: https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso?checksum=sha256%3Aea444d6f8ac95fd51d2aedb8015c57410d1ad19b494cedec6914c17fda02733c => /home/ladar/robox/packer_cache/a66b45ac1b44026fb265fcd819d79b4d87c68449.iso
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui: ==> generic-debian8-vmware: Creating required virtual machine disks
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 [INFO] Creating disk with Path: output/generic-debian8-vmware/generic-debian8-vmware.vmdk and Size: 32768M
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 Executing: /usr/bin/vmware-vdiskmanager -c -s 32768M -a lsilogic -t 0 output/generic-debian8-vmware/generic-debian8-vmware.vmdk
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 stdout: Creating disk 'output/generic-debian8-vmware/generic-debian8-vmware.vmdk'
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui: ==> generic-debian8-vmware: Building and writing VMX file
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 Writing VMX to: output/generic-debian8-vmware/generic-debian8-vmware.vmx
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 Writing VMX to: output/generic-debian8-vmware/generic-debian8-vmware.vmx
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui: ==> generic-debian8-vmware: Starting HTTP server on port 8921
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 Writing VMX to: output/generic-debian8-vmware/generic-debian8-vmware.vmx
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui: ==> generic-debian8-vmware: Starting virtual machine...
logs/generic-vmware-1.txt:2020/04/30 16:32:57 ui:     generic-debian8-vmware: The VM will be run headless, without a GUI. If you want to
logs/generic-vmware-1.txt:    generic-debian8-vmware: view the screen of the VM, connect via VNC with the password "" to
logs/generic-vmware-1.txt:    generic-debian8-vmware: vnc://127.0.0.1:5989
logs/generic-vmware-1.txt:2020/04/30 16:32:57 packer: 2020/04/30 16:32:57 Executing: /usr/bin/vmrun -T ws start output/generic-debian8-vmware/generic-debian8-vmware.vmx nogui
logs/generic-vmware-1.txt:2020/04/30 16:32:58 ui: ==> generic-debian8-vmware: Waiting 20s for boot...
logs/generic-vmware-1.txt:2020/04/30 16:33:18 ui: ==> generic-debian8-vmware: Connecting to VM via VNC (127.0.0.1:5989)
logs/generic-vmware-1.txt:2020/04/30 16:33:18 packer: 2020/04/30 16:33:18 Connected to VNC desktop: generic-debian8-vmware
logs/generic-vmware-1.txt:2020/04/30 16:33:18 ui: ==> generic-debian8-vmware: Typing the boot command over VNC...
logs/generic-vmware-1.txt:2020/04/30 16:33:44 ui: ==> generic-debian8-vmware: Using ssh communicator to connect: 172.16.203.140
logs/generic-vmware-1.txt:2020/04/30 16:33:44 ui: ==> generic-debian8-vmware: Waiting for SSH to become available...
logs/generic-vmware-1.txt:2020/04/30 17:33:44 ui error: ==> generic-debian8-vmware: Timeout waiting for SSH.
logs/generic-vmware-1.txt:2020/04/30 17:33:44 packer: /home/ladar/robox/output/generic-debian8-vmware/generic-debian8-vmware.vmx
logs/generic-vmware-1.txt:2020/04/30 17:33:44 ui: ==> generic-debian8-vmware: Stopping virtual machine...
logs/generic-vmware-1.txt:2020/04/30 17:33:44 packer: 2020/04/30 17:33:44 Executing: /usr/bin/vmrun -T ws stop output/generic-debian8-vmware/generic-debian8-vmware.vmx hard
logs/generic-vmware-1.txt:2020/04/30 17:33:45 ui: ==> generic-debian8-vmware: Deleting output directory...
logs/generic-vmware-1.txt:2020/04/30 17:33:45 ui error: Build 'generic-debian8-vmware' errored: Timeout waiting for SSH.
logs/generic-vmware-1.txt:2020/05/01 11:57:43 machine readable: generic-debian8-vmware,error []string{"Timeout waiting for SSH."}
logs/generic-vmware-1.txt:2020/05/01 11:57:43 ui error: --> generic-debian8-vmware: Timeout waiting for SSH.
logs/generic-libvirt-1.txt:2020/05/01 11:58:00 ui: generic-debian8-libvirt output will be in this color.
logs/generic-libvirt-1.txt:2020/05/01 11:58:00 Preparing build: generic-debian8-libvirt
logs/generic-libvirt-1.txt:2020/05/01 14:31:35 Parallelization disabled, waiting for build to finish: generic-debian8-libvirt
logs/generic-libvirt-1.txt:2020/05/01 14:31:35 Starting build run: generic-debian8-libvirt
logs/generic-libvirt-1.txt:2020/05/01 14:31:35 ui: ==> generic-debian8-libvirt: Retrieving ISO
logs/generic-libvirt-1.txt:2020/05/01 14:31:35 ui: ==> generic-debian8-libvirt: Trying https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso
logs/generic-libvirt-1.txt:2020/05/01 14:31:35 ui: ==> generic-debian8-libvirt: Trying https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso?checksum=sha256%3Aea444d6f8ac95fd51d2aedb8015c57410d1ad19b494cedec6914c17fda02733c
logs/generic-libvirt-1.txt:2020/05/01 14:31:41 ui: ==> generic-debian8-libvirt: https://gensho.ftp.acc.umu.se/mirror/cdimage/archive/8.11.1/amd64/iso-cd/debian-8.11.1-amd64-netinst.iso?checksum=sha256%3Aea444d6f8ac95fd51d2aedb8015c57410d1ad19b494cedec6914c17fda02733c => /home/ladar/robox/packer_cache/a66b45ac1b44026fb265fcd819d79b4d87c68449.iso
logs/generic-libvirt-1.txt:2020/05/01 14:31:41 ui: ==> generic-debian8-libvirt: Creating required virtual machine disks
logs/generic-libvirt-1.txt:2020/05/01 14:31:41 packer: 2020/05/01 14:31:41 [INFO] Creating disk with Path: output/generic-debian8-libvirt/generic-debian8-libvirt and Size: 32768M
logs/generic-libvirt-1.txt:2020/05/01 14:31:41 packer: 2020/05/01 14:31:41 Executing qemu-img: []string{"create", "-f", "qcow2", "output/generic-debian8-libvirt/generic-debian8-libvirt", "32768M"}
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 packer: 2020/05/01 14:31:45 stdout: Formatting 'output/generic-debian8-libvirt/generic-debian8-libvirt', fmt=qcow2 size=34359738368 cluster_size=65536 lazy_refcounts=off refcount_bits=16
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui: ==> generic-debian8-libvirt: Starting HTTP server on port 8340
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui: ==> generic-debian8-libvirt: Found port for communicator (SSH, WinRM, etc): 3879.
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui: ==> generic-debian8-libvirt: Looking for available port between 5900 and 6000 on 127.0.0.1
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui: ==> generic-debian8-libvirt: Starting VM, booting from CD-ROM
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui:     generic-debian8-libvirt: The VM will be run headless, without a GUI. If you want to
logs/generic-libvirt-1.txt:    generic-debian8-libvirt: view the screen of the VM, connect via VNC without a password to
logs/generic-libvirt-1.txt:    generic-debian8-libvirt: vnc://127.0.0.1:5913
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 ui: ==> generic-debian8-libvirt: Overriding defaults Qemu arguments with QemuArgs...
logs/generic-libvirt-1.txt:2020/05/01 14:31:45 packer: 2020/05/01 14:31:45 Executing /usr/libexec/qemu-kvm: []string{"-machine", "type=pc,accel=kvm", "-drive", "if=none,file=output/generic-debian8-libvirt/generic-debian8-libvirt,id=drive0,cache=unsafe,discard=unmap,detect-zeroes=unmap,format=qcow2", "-m", "2048M", "-name", "generic-debian8-libvirt", "-netdev", "user,id=user.0,hostfwd=tcp::3879-:22", "-device", "virtio-scsi-pci,id=scsi0", "-device", "scsi-hd,bus=scsi0.0,drive=drive0", "-device", "virtio-net,netdev=user.0", "-cdrom", "/home/ladar/robox/packer_cache/a66b45ac1b44026fb265fcd819d79b4d87c68449.iso", "-boot", "once=d", "-smp", "cpus=2,sockets=2", "-vnc", "127.0.0.1:13"}
logs/generic-libvirt-1.txt:2020/05/01 14:31:47 ui: ==> generic-debian8-libvirt: Waiting 20s for boot...
logs/generic-libvirt-1.txt:2020/05/01 14:32:07 ui: ==> generic-debian8-libvirt: Connecting to VM via VNC (127.0.0.1:5913)
logs/generic-libvirt-1.txt:2020/05/01 14:32:07 packer: 2020/05/01 14:32:07 Connected to VNC desktop: QEMU (generic-debian8-libvirt)
logs/generic-libvirt-1.txt:2020/05/01 14:32:07 ui: ==> generic-debian8-libvirt: Typing the boot command over VNC...
logs/generic-libvirt-1.txt:2020/05/01 14:32:32 ui: ==> generic-debian8-libvirt: Using ssh communicator to connect: 127.0.0.1
logs/generic-libvirt-1.txt:2020/05/01 14:32:32 ui: ==> generic-debian8-libvirt: Waiting for SSH to become available...
logs/generic-libvirt-1.txt:2020/05/01 15:32:32 ui error: ==> generic-debian8-libvirt: Timeout waiting for SSH.
logs/generic-libvirt-1.txt:2020/05/01 15:32:32 ui: ==> generic-debian8-libvirt: Deleting output directory...
logs/generic-libvirt-1.txt:2020/05/01 15:32:32 ui error: Build 'generic-debian8-libvirt' errored: Timeout waiting for SSH.
```

**Comment by timschumi** [comment]
Digging into the syslog ([relevant snippet](https://gist.github.com/timschumi/b195c02780ace65f4936f77d92718bf0)), it appears that a number of signing keys recently (around the end of April) expired. Setting back the time in the recovery console (I set it to 2019/05/01 where every key I could see should still be valid) and restarting the installation from the failed step seems to work, but it obviously isn't a solution. Unfortunately, my keyboard layout in VNC is scrambled, so my debugging ability is limited at the moment.

**Comment by timschumi** [comment]
It seems like specifically the Debian jessie keys for the archive.debian.org mirror are expired. The "default mirror" still works fine: #146

**Pull request merged**
