### PR TITLE
Experimental/evilpot

### PR DESCRIPTION
**Pull request by klosnet**
gr

### CODE REVIEW

**Comment by ladar** [comment]
No clue what this pull request is trying to do. IOn first glance it appears to be undoing a lot of work/clearnup that was done during the last merge.

**Comment by ladar** [comment]
No clue what this pull request is trying to do. At first glance the pull request appears to be undoing a lot of work/cleanup that was done during the last merge, namely renaming boxes to use the `evil-honeypot-PROVIDER` scheme. 

Remember, `evil` is the namespace (or organization), `honeypot` is the box name, and the provider is `hyperv|libvirt|vmware|virtualbox` ... the nickname `evilpot` was really just for internal use, as a shorthand way of saying `evil-honeypot` ...

**Comment by ladar** [comment]
As such the `Vagrantfile` template should be called `evil-honeypot.rb` ... as for the Ubuntun installer config file, we can reuse the existing `generic.ubuntu1604.vagrant.cfg` template, or if a different collection of settings is required, we can start a file naming convention, like `evil.honeypot.ubuntu1604.vagrant.cfg` or `evil.ubuntu1604.vagrant.cfg` or `honeypot.ubuntu1604.vagrant.cfg` ... which scheme makes the most sense depends on how many `evil` boxes we'll need and whether they can share the Ubuntu install config ... or need unique settings that can't be setup via the script module later on.

**Comment by klosnet** [comment]
> No clue what this pull request is trying to do. At first glance the pull request appears to be undoing a lot of work/cleanup that was done during the last merge, namely renaming boxes to use the `evil-honeypot-PROVIDER` scheme.
> 
> Remember, `evil` is the namespace (or organization), `honeypot` is the box name, and the provider is `hyperv|libvirt|vmware|virtualbox` ... the nickname `evilpot` was really just for internal use, as a shorthand way of saying `evil-honeypot` ...

Yep, thats where I messed up.

**Comment by ladar** [comment]
Can you resolve the conflicts?

**Comment by klosnet** [comment]
> Can you resolve the conflicts?

pushed the evil-honeypot.rb. is it best practice to build the inetsim installation into the packer build, or leave it in the provisioner section in the Vagrantfile?

**Comment by klosnet** [comment]
> Can you resolve the conflicts?

Sorry for the n00b question here...but how can I view what the actual conflicts are?

**Pull request closed without merging**
